[package]
name = "safa-api"
version = "0.6.1"
edition = "2024"
repository = "https://github.com/SafaOS/safa-api"
categories = ["os"]
keywords = ["kernel", "libos"]
license = "MIT"
description = "A high-level API over SafaOS's syscalls"

[lib]
test = false

[dependencies]
safa-abi = { version = "0.6.0", git = "https://github.com/SafaOS/safa-abi" }
simpldns = { version = "0.1", git  = "https://github.com/safiworks/simpldns" }
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
alloc = { version = "1.0.0", optional = true, package = "rustc-std-workspace-alloc" }
talc =  { version = "5.0.4", optional = true }
lock_api = { version = "0.4.14", optional = true }
dlmalloc = { version = "0.2.14", optional = true }


[features]
default = ["lock_api", "dlmalloc"]

std = ["safa-abi/std"]
linkonce = []

rustc-dep-of-std = [
    "core",
    "alloc",
    "dlmalloc",
    "safa-abi/rustc-dep-of-std",
    "simpldns/rustc-dep-of-std",
    "dlmalloc/rustc-dep-of-std",
    "linkonce",
]

talc = [
    "dep:talc",
    "dep:lock_api"
]
lock_api = ["dep:lock_api"]
dlmalloc = ["dep:dlmalloc"]

[package.metadata.docs.rs]

default-target = "x86_64-unknown-none"
targets = []

[profile.release]
lto = true
